package com.hp.titan.mytitan.model;

// Generated Dec 1, 2013 1:05:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CaseLog generated by hbm2java
 */
public class CommitReport implements java.io.Serializable {
	
	private String commitreportId;
	private String reportaryId;
	private Integer revision;
	private String committedBy;
	private Date commitTime;
	private String codeChange;
	private String comment;
	public String getCommitreportId() {
		return commitreportId;
	}
	public void setCommitreportId(String commitreportId) {
		this.commitreportId = commitreportId;
	}
	public String getReportaryId() {
		return reportaryId;
	}
	public void setReportaryId(String reportaryId) {
		this.reportaryId = reportaryId;
	}
	public String getCommittedBy() {
		return committedBy;
	}
	public void setCommittedBy(String committedBy) {
		this.committedBy = committedBy;
	}
	public Date getCommitTime() {
		return commitTime;
	}
	public void setCommitTime(Date commitTime) {
		this.commitTime = commitTime;
	}
	public String getCodeChange() {
		return codeChange;
	}
	public void setCodeChange(String codeChange) {
		this.codeChange = codeChange;
	}
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}
	public Integer getRevision() {
		return revision;
	}
	public void setRevision(Integer revision) {
		this.revision = revision;
	}
}
