package com.hp.titan.mytitan.model;

// Generated Dec 1, 2013 1:05:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CaseLog generated by hbm2java
 */
public class CommitPath implements java.io.Serializable {
	
	private String commitpathId;
	private String commitreportId;
	private String path;
	private String codeChange;
	
	public String getCodeChange() {
		return codeChange;
	}
	public void setCodeChange(String codeChange) {
		this.codeChange = codeChange;
	}
	public String getCommitpathId() {
		return commitpathId;
	}
	public void setCommitpathId(String commitpathId) {
		this.commitpathId = commitpathId;
	}
	public String getCommitreportId() {
		return commitreportId;
	}
	public void setCommitreportId(String commitreportId) {
		this.commitreportId = commitreportId;
	}
	public String getPath() {
		return path;
	}
	public void setPath(String path) {
		this.path = path;
	}
}
