package com.hp.titan.mytitan.model;

// Generated Dec 1, 2013 1:05:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CaseLog generated by hbm2java
 */
public class Consumption implements java.io.Serializable {
	
	private String consumeId;
	private Integer userId;
	private String goodsName;
	private Integer price;
	private String status;
	private Date consumeDate;
	private String strConsumeDate;
	private String userCode;
	private Integer selectedNum;
	private Integer isValid;
	private Integer type;
	public String getGoodsName() {
		return goodsName;
	}
	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}
	public Integer getPrice() {
		return price;
	}
	public void setPrice(Integer price) {
		this.price = price;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public Date getConsumeDate() {
		return consumeDate;
	}
	public void setConsumeDate(Date consumeDate) {
		this.consumeDate = consumeDate;
	}
	public Integer getIsValid() {
		return isValid;
	}
	public void setIsValid(Integer isValid) {
		this.isValid = isValid;
	}
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	public String getConsumeId() {
		return consumeId;
	}
	public void setConsumeId(String consumeId) {
		this.consumeId = consumeId;
	}
	public String getUserCode() {
		return userCode;
	}
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}
	public String getStrConsumeDate() {
		return strConsumeDate;
	}
	public void setStrConsumeDate(String strConsumeDate) {
		this.strConsumeDate = strConsumeDate;
	}
	public Integer getSelectedNum() {
		return selectedNum;
	}
	public void setSelectedNum(Integer selectedNum) {
		this.selectedNum = selectedNum;
	}
	public Integer getType() {
		return type;
	}
	public void setType(Integer type) {
		this.type = type;
	}
	
}
