package com.hp.titan.mytitan.model;

// Generated Dec 1, 2013 1:05:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CaseLog generated by hbm2java
 */
public class ExpLog implements java.io.Serializable {
	
	private String expLogId;
	private Integer expValue;
	private Integer expTotal;
	private String expType;
	private String detail;
	private Integer userId;
	private Date createDate;
	private Integer isValid;
	
	
	public String getExpLogId() {
		return expLogId;
	}
	public void setExpLogId(String expLogId) {
		this.expLogId = expLogId;
	}
	public Integer getExpValue() {
		return expValue;
	}
	public void setExpValue(Integer expValue) {
		this.expValue = expValue;
	}
	public Integer getExpTotal() {
		return expTotal;
	}
	public void setExpTotal(Integer expTotal) {
		this.expTotal = expTotal;
	}
	public String getExpType() {
		return expType;
	}
	public void setExpType(String expType) {
		this.expType = expType;
	}
	public String getDetail() {
		return detail;
	}
	public void setDetail(String detail) {
		this.detail = detail;
	}
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	public Integer getIsValid() {
		return isValid;
	}
	public void setIsValid(Integer isValid) {
		this.isValid = isValid;
	}

}
