package com.hp.titan.mytitan.model;

// Generated Dec 1, 2013 1:05:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CaseLog generated by hbm2java
 */
public class PointHist implements java.io.Serializable {
	
	private String pointHistId;
	private Integer pointFare;
	private Integer pointTotal;
	private String type;
	private String objectId;
	private Integer userId;
	private Date createDate;
	private Integer isValid;
	private String strcreateDate;

	public String getObjectId() {
		return objectId;
	}
	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}
	public String getPointHistId() {
		return pointHistId;
	}
	public void setPointHistId(String pointHistId) {
		this.pointHistId = pointHistId;
	}
	public Integer getPointFare() {
		return pointFare;
	}
	public void setPointFare(Integer pointFare) {
		this.pointFare = pointFare;
	}
	public Integer getPointTotal() {
		return pointTotal;
	}
	public void setPointTotal(Integer pointTotal) {
		this.pointTotal = pointTotal;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public Integer getIsValid() {
		return isValid;
	}
	public void setIsValid(Integer isValid) {
		this.isValid = isValid;
	}
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	public String getStrcreateDate() {
		return strcreateDate;
	}
	public void setStrcreateDate(String strcreateDate) {
		this.strcreateDate = strcreateDate;
	}
}
