package com.hp.titan.mytitan.model;

// Generated Dec 1, 2013 1:05:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CaseLog generated by hbm2java
 */
public class ProjectRallyQuix implements java.io.Serializable {
	private String rallyquixId;
	private String projectId;
	private String nameinRally;
	private String nameinQuix;
	private String autoRefresh;
	private String component;
	private Integer isValid=0;
	public String getProjectId() {
		return projectId;
	}
	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}
	public String getNameinRally() {
		return nameinRally;
	}
	public void setNameinRally(String nameinRally) {
		this.nameinRally = nameinRally;
	}
	public String getNameinQuix() {
		return nameinQuix;
	}
	public void setNameinQuix(String nameinQuix) {
		this.nameinQuix = nameinQuix;
	}
	public String getAutoRefresh() {
		return autoRefresh;
	}
	public void setAutoRefresh(String autoRefresh) {
		this.autoRefresh = autoRefresh;
	}
	public String getRallyquixId() {
		return rallyquixId;
	}
	public void setRallyquixId(String rallyquixId) {
		this.rallyquixId = rallyquixId;
	}
	public String getComponent() {
		return component;
	}
	public void setComponent(String component) {
		this.component = component;
	}
	public Integer getIsValid() {
		return isValid;
	}
	public void setIsValid(Integer isValid) {
		this.isValid = isValid;
	}
}
