package com.hp.titan.mytitan.model;

// Generated Dec 1, 2013 1:05:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CaseLog generated by hbm2java
 */
public class Reportary implements java.io.Serializable {
	
	private String reportaryId;
	private String projectId;
	private String svnUrl;
	private String remark;
	private String userName;
	private String pwd;
	private String moduleId;
	private String moduleName;
	private String autoRefresh;
	private Date beginDate;
	private Integer isValid=0;
	public String getReportaryId() {
		return reportaryId;
	}
	public void setReportaryId(String reportaryId) {
		this.reportaryId = reportaryId;
	}
	public String getSvnUrl() {
		return svnUrl;
	}
	public void setSvnUrl(String svnUrl) {
		this.svnUrl = svnUrl;
	}
	public Integer getIsValid() {
		return isValid;
	}
	public void setIsValid(Integer isValid) {
		this.isValid = isValid;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public String getProjectId() {
		return projectId;
	}
	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}
	public Date getBeginDate() {
		return beginDate;
	}
	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getPwd() {
		return pwd;
	}
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
	public String getModuleId() {
		return moduleId;
	}
	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}
	public String getModuleName() {
		return moduleName;
	}
	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}
	public String getAutoRefresh() {
		return autoRefresh;
	}
	public void setAutoRefresh(String autoRefresh) {
		this.autoRefresh = autoRefresh;
	}

}
