package com.hp.titan.mytitan.model;

// Generated Dec 1, 2013 1:05:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CaseLog generated by hbm2java
 */
public class WeeklyReportTask implements java.io.Serializable {
	
	private String reporttaskId;
	private String reportId;
	private String taskType;
	private String actuals;
	private String todo;
	private String percent;
	private String parent;
	private String taskName;
	private String desciption;
	private String state;

	public WeeklyReportTask() {
	}

	public String getReporttaskId() {
		return reporttaskId;
	}

	public void setReporttaskId(String reporttaskId) {
		this.reporttaskId = reporttaskId;
	}

	public String getReportId() {
		return reportId;
	}

	public void setReportId(String reportId) {
		this.reportId = reportId;
	}

	public String getTaskType() {
		return taskType;
	}

	public void setTaskType(String taskType) {
		this.taskType = taskType;
	}

	public String getTaskName() {
		return taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	public String getDesciption() {
		return desciption;
	}

	public void setDesciption(String desciption) {
		this.desciption = desciption;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getActuals() {
		return actuals;
	}

	public void setActuals(String actuals) {
		this.actuals = actuals;
	}

	public String getTodo() {
		return todo;
	}

	public void setTodo(String todo) {
		this.todo = todo;
	}

	public String getPercent() {
		return percent;
	}

	public void setPercent(String percent) {
		this.percent = percent;
	}

	public String getParent() {
		return parent;
	}

	public void setParent(String parent) {
		this.parent = parent;
	}
}
