package com.hp.titan.common.vo;

// Generated Dec 1, 2013 1:05:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CaseLog generated by hbm2java
 */
public class DefectVo implements java.io.Serializable {
	
	private String formattedId;
	private String defectNum;
	private String defectName;
	private String state;
	private String priority;
	private String submittedBy;
	private String submittedbyObjectid;
	private String developer;
	private String objectId;
	private String lastupdateDate;
	private String addUrl;
	private String projectName;
	private String component;
	private String userStory;
	private String submitDate;
	public String getFormattedId() {
		return formattedId;
	}
	public void setFormattedId(String formattedId) {
		this.formattedId = formattedId;
	}
	public String getDefectNum() {
		return defectNum;
	}
	public void setDefectNum(String defectNum) {
		this.defectNum = defectNum;
	}
	public String getDefectName() {
		return defectName;
	}
	public void setDefectName(String defectName) {
		this.defectName = defectName;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	public String getPriority() {
		return priority;
	}
	public void setPriority(String priority) {
		this.priority = priority;
	}
	public String getSubmittedBy() {
		return submittedBy;
	}
	public void setSubmittedBy(String submittedBy) {
		this.submittedBy = submittedBy;
	}
	public String getDeveloper() {
		return developer;
	}
	public void setDeveloper(String developer) {
		this.developer = developer;
	}
	public String getObjectId() {
		return objectId;
	}
	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}
	public String getLastupdateDate() {
		return lastupdateDate;
	}
	public void setLastupdateDate(String lastupdateDate) {
		this.lastupdateDate = lastupdateDate;
	}
	public String getSubmittedbyObjectid() {
		return submittedbyObjectid;
	}
	public void setSubmittedbyObjectid(String submittedbyObjectid) {
		this.submittedbyObjectid = submittedbyObjectid;
	}
	public String getAddUrl() {
		return addUrl;
	}
	public void setAddUrl(String addUrl) {
		this.addUrl = addUrl;
	}
	public String getProjectName() {
		return projectName;
	}
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}
	public String getComponent() {
		return component;
	}
	public void setComponent(String component) {
		this.component = component;
	}
	public String getUserStory() {
		return userStory;
	}
	public void setUserStory(String userStory) {
		this.userStory = userStory;
	}
	public String getSubmitDate() {
		return submitDate;
	}
	public void setSubmitDate(String submitDate) {
		this.submitDate = submitDate;
	}
}
