package com.hp.titan.test.model;

// Generated Dec 4, 2013 5:55:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Parameter generated by hbm2java
 */
public class DefaultParameter implements java.io.Serializable {

	private DefaultParameterId id;
	private String defaultValue;

	public DefaultParameter() {
	}

	public String getDefaultValue() {
		return defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	public DefaultParameterId getId() {
		return id;
	}

	public void setId(DefaultParameterId id) {
		this.id = id;
	}



}
