package com.hp.titan.test.model;

// Generated Dec 4, 2013 5:55:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Parameter generated by hbm2java
 */
public class DefaultParameterId implements java.io.Serializable {

	private Integer userId;
	private String paradataName;
	private String testjobId;

	public DefaultParameterId() {
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getParadataName() {
		return paradataName;
	}

	public void setParadataName(String paradataName) {
		this.paradataName = paradataName;
	}

	public String getTestjobId() {
		return testjobId;
	}

	public void setTestjobId(String testjobId) {
		this.testjobId = testjobId;
	}

}
