package com.hp.titan.test.model;

// Generated Dec 4, 2013 5:55:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Parameter generated by hbm2java
 */
public class ParameterData implements java.io.Serializable {

	private String paradataId;
	private String type;
	private String paradataName;
	private String jenkins;
	private String projectId;

	public ParameterData() {
	}

	public String getParadataId() {
		return paradataId;
	}

	public void setParadataId(String paradataId) {
		this.paradataId = paradataId;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getParadataName() {
		return paradataName;
	}

	public void setParadataName(String paradataName) {
		this.paradataName = paradataName;
	}

	public String getJenkins() {
		return jenkins;
	}

	public void setJenkins(String jenkins) {
		this.jenkins = jenkins;
	}

	public String getProjectId() {
		return projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}


}
