package com.hp.titan.test.model;
// default package
// Generated 2010-5-26 17:40:21 by Hibernate Tools 3.3.0.GA

/**
 * UserRoleId generated by hbm2java
 */
public class RunCaseServerId implements java.io.Serializable {


	private String caseId;
	private String serverData;
	private String dedicatedserverId;
	public RunCaseServerId() {
	}
	public RunCaseServerId(String caseId, String serverData, String dedicatedserverId) {
		this.caseId = caseId;
		this.serverData = serverData;
		this.dedicatedserverId = dedicatedserverId;
	}
	public String getCaseId() {
		return caseId;
	}
	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}
	public String getServerData() {
		return serverData;
	}
	public void setServerData(String serverData) {
		this.serverData = serverData;
	}
	public String getDedicatedserverId() {
		return dedicatedserverId;
	}
	public void setDedicatedserverId(String dedicatedserverId) {
		this.dedicatedserverId = dedicatedserverId;
	}



}
