package com.hp.titan.test.model;
// default package
// Generated 2010-5-26 17:40:21 by Hibernate Tools 3.3.0.GA

/**
 * UserRoleId generated by hbm2java
 */
public class TestJobPlanId implements java.io.Serializable {


	private String testplanId;
	private String testjobId;
	public TestJobPlanId() {
	}

	public TestJobPlanId(String testplanId, String testjobId) {
		this.testplanId = testplanId;
		this.testjobId = testjobId;
	}

	public String getTestjobId() {
		return testjobId;
	}

	public void setTestjobId(String testjobId) {
		this.testjobId = testjobId;
	}

	public String getTestplanId() {
		return testplanId;
	}

	public void setTestplanId(String testplanId) {
		this.testplanId = testplanId;
	}

}
