package com.hp.titan.test.model;

/**
 * UserRoleId generated by hbm2java
 */
public class TestJobServerId implements java.io.Serializable {


	private String testjobId;
	private String serverId;
	public TestJobServerId() {
	}

	public TestJobServerId(String testjobId, String serverId) {
		this.testjobId = testjobId;
		this.serverId = serverId;
	}

	public String getTestjobId() {
		return testjobId;
	}

	public void setTestjobId(String testjobId) {
		this.testjobId = testjobId;
	}

	public String getServerId() {
		return serverId;
	}

	public void setServerId(String serverId) {
		this.serverId = serverId;
	}




}
