package com.hp.titan.test.model;
// default package
// Generated 2010-5-26 17:40:21 by Hibernate Tools 3.3.0.GA

/**
 * UserRoleId generated by hbm2java
 */
public class TestJobCaseId implements java.io.Serializable {


	private String testcaseId;
	private String testjobId;
	public TestJobCaseId() {
	}

	public TestJobCaseId(String testcaseId, String testjobId) {
		this.testcaseId = testcaseId;
		this.testjobId = testjobId;
	}

	public String getTestcaseId() {
		return testcaseId;
	}

	public void setTestcaseId(String testcaseId) {
		this.testcaseId = testcaseId;
	}

	public String getTestjobId() {
		return testjobId;
	}

	public void setTestjobId(String testjobId) {
		this.testjobId = testjobId;
	}

}
