package com.hp.titan.project.model;
// default package
// Generated 2010-5-26 17:40:21 by Hibernate Tools 3.3.0.GA

/**
 * UserRoleId generated by hbm2java
 */
public class CommitusDefectId implements java.io.Serializable {


	private String commitreportId;
	private String usdefectNum;
	public CommitusDefectId() {
	}
	public String getCommitreportId() {
		return commitreportId;
	}
	public void setCommitreportId(String commitreportId) {
		this.commitreportId = commitreportId;
	}
	public String getUsdefectNum() {
		return usdefectNum;
	}
	public void setUsdefectNum(String usdefectNum) {
		this.usdefectNum = usdefectNum;
	}

}
