package com.hp.titan.auth.model;
// default package
// Generated 2010-5-26 17:40:21 by Hibernate Tools 3.3.0.GA

/**
 * UserRoleId generated by hbm2java
 */
public class RoleAuthId implements java.io.Serializable {


	private String roleId;
	private String authId;
	public RoleAuthId() {
	}

	public RoleAuthId(String roleId, String authId) {
		this.authId = authId;
		this.roleId = roleId;
	}

	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getAuthId() {
		return authId;
	}

	public void setAuthId(String authId) {
		this.authId = authId;
	}
 

	 

}
