package com.hp.titan.auth.model;
// default package
// Generated 2010-5-26 17:40:21 by Hibernate Tools 3.3.0.GA

/**
 * UserRoleId generated by hbm2java
 */
public class UserProjectId implements java.io.Serializable {


	private String projectId;
	private Integer userId;
	public UserProjectId() {
	}

	public UserProjectId(Integer userId, String projectId) {
		this.projectId = projectId;
		this.userId = userId;
	}


	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getProjectId() {
		return projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	 

	 

}
