package com.hp.titan.auth.model;
// default package
// Generated 2010-5-26 17:40:21 by Hibernate Tools 3.3.0.GA

/**
 * UserRoleId generated by hbm2java
 */
public class UserGroupId implements java.io.Serializable {


	private Integer groupId;
	private Integer userId;
	public UserGroupId() {
	}

	public UserGroupId(Integer userId, Integer groupId) {
		this.groupId = groupId;
		this.userId = userId;
	}

	public Integer getGroupId() {
		return groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	 

	 

}
