package com.hp.titan.auth.model;

// default package
// Generated 2010-5-26 17:40:21 by Hibernate Tools 3.3.0.GA

/**
 * UserRoleId generated by hbm2java
 */
public class UserRoleId implements java.io.Serializable {

	private Integer userId;
	private String roleId;

	public UserRoleId() {
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

}
