package com.hp.titan.test.vo;

// Generated Dec 1, 2013 1:05:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CaseLog generated by hbm2java
 */
public class DefectInfoVo implements java.io.Serializable {
	
	private String defectNum;
	private String defectName;
	private String state;
	private String priority;
	private String submittedBy;
	private String submittEmail;
	private String developer;
	private String developerEmail;
	private String inputDate;
	private String testcaseName;
	private String testjobName;
	public String getDefectNum() {
		return defectNum;
	}
	public void setDefectNum(String defectNum) {
		this.defectNum = defectNum;
	}
	public String getDefectName() {
		return defectName;
	}
	public void setDefectName(String defectName) {
		this.defectName = defectName;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	public String getPriority() {
		return priority;
	}
	public void setPriority(String priority) {
		this.priority = priority;
	}
	public String getSubmittedBy() {
		return submittedBy;
	}
	public void setSubmittedBy(String submittedBy) {
		this.submittedBy = submittedBy;
	}
	public String getSubmittEmail() {
		return submittEmail;
	}
	public void setSubmittEmail(String submittEmail) {
		this.submittEmail = submittEmail;
	}
	public String getDeveloper() {
		return developer;
	}
	public void setDeveloper(String developer) {
		this.developer = developer;
	}
	public String getDeveloperEmail() {
		return developerEmail;
	}
	public void setDeveloperEmail(String developerEmail) {
		this.developerEmail = developerEmail;
	}
	public String getInputDate() {
		return inputDate;
	}
	public void setInputDate(String inputDate) {
		this.inputDate = inputDate;
	}
	public String getTestcaseName() {
		return testcaseName;
	}
	public void setTestcaseName(String testcaseName) {
		this.testcaseName = testcaseName;
	}
	public String getTestjobName() {
		return testjobName;
	}
	public void setTestjobName(String testjobName) {
		this.testjobName = testjobName;
	}
}
